// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend_notes.Models;

public partial class Note
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }
    public int IsArchive { get; set; }

    public int IdAccount { get; set; }

    public int? IdTag { get; set; }

    public virtual Account Account { get; set; }

    public virtual Tag Tag { get; set; }
}